part of vcl;

const MESSAGE TCM_GETITEMCOUNT       = MESSAGE(0x1304, 'TCM_GETITEMCOUNT');
const MESSAGE TCM_DELETEITEM         = MESSAGE(0x1308, 'TCM_DELETEITEM');
const MESSAGE TCM_DELETEALLITEMS     = MESSAGE(0x1309, 'TCM_DELETEALLITEMS');

const MESSAGE TCM_GETCURSEL          = MESSAGE(0x1311, 'TCM_GETCURSEL');
const MESSAGE TCM_SETCURSEL          = MESSAGE(0x1312, 'TCM_SETCURSEL');
